/**
 * MATERIALISE `@orbitmines/physics` INSIDE THIS REPOSITORY, instead of linking out to it.
 *
 * The package is `../../physics/languages/physics.ts` - GENERATED by `npx ray gen` there from the
 * `.ray` definitions; nothing in it is written by hand, and nothing here edits it. It is a `file:`
 * dependency during development, which npm installs as a SYMLINK. Turbopack will not follow a
 * symlink out of its filesystem root, so the root had to be widened to the folder holding both
 * repositories - and that folder is three hundred gigabytes across seventeen repositories, most of
 * it archives. Turbopack watches its whole root, so the dev server was opening file handles for
 * all of it until Node's async-hooks map hit its ceiling and the process died with
 * `RangeError: Map maximum size exceeded`.
 *
 * NEXT HAS NO WATCH IGNORE for Turbopack - `watchOptions` carries a poll interval and nothing
 * else - so the root cannot be kept and narrowed. It has to become this repository, which
 * means the package has to BE here rather than point away.
 *
 * SO THE SYMLINK IS REPLACED BY A COPY, of exactly what the package's own `files` field says
 * it ships. Nothing else changes: the import specifier, `transpilePackages` and the type
 * resolution all work on a real directory in `node_modules` the way they worked on a link,
 * and the watched tree is this repository alone.
 *
 * AND THE VISUALS COME ALONG. `npx ray visuals` renders every visual the theories declare into
 * `../../physics/visuals/<id>/animation.webm` + `snapshot.png`; the package's `Film` component plays
 * them from `/visuals/<id>/...`, so those two files per visual are copied into `public/visuals/`
 * (gitignored: it is generated output, the source is the `.ray`).
 *
 * IT IS A COPY, SO IT WOULD GO STALE - so `npm run dev` never lets it: it runs this with
 * `--watch -- next dev`, which copies once, starts the dev server, and re-copies whenever
 * `npx ray gen` (or `npx ray visuals`) writes into ../physics, for as long as the server runs.
 * `prebuild` copies once before a build. `npm run sync:physics` is the one-off by hand.
 *
 * ONLY WHAT CHANGED IS WRITTEN, and only what is gone is removed. The package is never
 * deleted and put back: a dev server that looks while it is half-copied sees a package with
 * no `index.ts` and fails the page, and every untouched file rewritten is a recompile of it.
 */
import { spawn } from "node:child_process";
import { copyFileSync, existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, watch } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const physics = resolve(here, "../../../physics");
const from = join(physics, "languages", "physics.ts");
const visuals = join(physics, "visuals");
const to = resolve(here, "../node_modules/@orbitmines/physics");
const toVisuals = resolve(here, "../public/visuals");

if (!existsSync(from)) {
  console.error(`sync:physics - no package at ${from} (run \`npx ray gen\` in ../physics)`);
  process.exit(1);
}

/* what the package says it ships, plus the manifest that says it */
const ships = () => [
  ...JSON.parse(readFileSync(join(from, "package.json"), "utf8")).files ?? [],
  "package.json",
];

/* the files a page plays of a visual: the film and its last frame */
const PLAYED = ["animation.webm", "snapshot.png"];

/* every file under `dir`, by its path relative to `root` */
const files = (dir, root = dir, out = new Map()) => {
  if (!existsSync(dir)) return out;
  if (!statSync(dir).isDirectory()) return out.set(relative(root, dir), dir);
  for (const f of readdirSync(dir)) files(join(dir, f), root, out);
  return out;
};

/* make `to` hold exactly `want` (relative path -> source), writing only what differs */
const mirror = (want, to) => {
  /* a symlink is removed rather than written through, or the copy lands in the other repo */
  if (lstatSync(to, { throwIfNoEntry: false })?.isSymbolicLink()) rmSync(to, { force: true });
  let wrote = 0, removed = 0;
  for (const [rel, src] of want) {
    const dst = join(to, rel);
    const a = statSync(src), b = statSync(dst, { throwIfNoEntry: false });
    if (b && a.size === b.size && readFileSync(src).equals(readFileSync(dst))) continue;
    mkdirSync(dirname(dst), { recursive: true });
    copyFileSync(src, dst);
    wrote++;
  }
  for (const rel of files(to).keys()) {
    if (want.has(rel)) continue;
    rmSync(join(to, rel), { force: true });
    removed++;
  }
  return `${want.size} files, ${wrote} written, ${removed} removed`;
};

const sync = () => {
  const pkg = new Map();
  for (const f of ships()) for (const [rel, src] of files(join(from, f), from)) pkg.set(rel, src);
  console.log(`sync:physics - node_modules/@orbitmines/physics: ${mirror(pkg, to)}`);

  const films = new Map();
  if (existsSync(visuals)) {
    for (const id of readdirSync(visuals)) {
      for (const f of PLAYED) {
        const src = join(visuals, id, f);
        if (existsSync(src)) films.set(join(id, f), src);
      }
    }
  }
  console.log(`sync:physics - public/visuals: ${mirror(films, toVisuals)}`);
};

sync();

if (process.argv.includes("--watch")) {
  let queued = null;
  console.log(`sync:physics - watching ${from} and ${visuals}`);
  const watchers = [from, visuals].filter(existsSync).map(dir =>
    watch(dir, { recursive: true }, (_, file) => {
      if (file?.startsWith("node_modules") || file?.startsWith(".git")) return;
      /* a generator writes many files in a burst: copy once it has gone quiet */
      clearTimeout(queued);
      queued = setTimeout(() => { try { sync(); } catch (e) { console.error(`sync:physics - ${e.message}`); } }, 300);
    }));

  /* `-- <command>`: run it alongside, and stop watching when it stops */
  const at = process.argv.indexOf("--");
  if (at >= 0 && process.argv[at + 1]) {
    const [cmd, ...args] = process.argv.slice(at + 1);
    const child = spawn(cmd, args, { stdio: "inherit", shell: process.platform === "win32" });
    const stop = code => { watchers.forEach(w => w.close()); clearTimeout(queued); process.exit(code ?? 0); };
    child.on("exit", (code, signal) => stop(code ?? (signal ? 1 : 0)));
    for (const sig of ["SIGINT", "SIGTERM"]) process.on(sig, () => child.kill(sig));
  }
}
