import _ from "lodash";

export type Styles = { [key: string]: string };

const computeExplicitStyles = (element: Element, parent?: Element): Styles => {
  const isTopLevel = parent === undefined;

  const styles = getComputedStyle(element);
  const parentStyles = !isTopLevel && element.parentElement
    ? getComputedStyle(element.parentElement)
    : null;

  const keys: string[] = _.values(styles) as string[];

  const computedStyles = _.fromPairs<string>(keys
    .map<[string, string]>(key => [key, styles.getPropertyValue(key)])
    .filter(pair => {
      const [key, value] = pair;

      if (_.isEmpty(value))
        return false;

      // TODO: These are all useful initial drafts, they're not foolproof.

      // Exclude if inferable from other styles on the same element
      if (isInferable(styles, key, value))
        return false;

      // Exclude if inheritable from parent
      if (isInheritable(key) && parentStyles?.getPropertyValue(key) === value)
        return false;

      // Exclude if it's a default value
      if (isDefault(key, value))
        return false;

      return true;
    })
  );

  return computedStyles;
}
export default computeExplicitStyles;

export const defaultStyles: Styles = {
  "accent-color": "auto",
  "align-content": "normal",
  "align-items": "normal",
  "align-self": "auto",
  "alignment-baseline": "auto",
  "animation-delay": "0s",
  "animation-direction": "normal",
  "animation-duration": "0s",
  "animation-fill-mode": "none",
  "animation-iteration-count": "1",
  "animation-name": "none",
  "animation-play-state": "running",
  "animation-timing-function": "ease",
  "app-region": "none",
  "appearance": "none",
  "backdrop-filter": "none",
  "backface-visibility": "visible",
  "background-attachment": "scroll",
  "background-blend-mode": "normal",
  "background-clip": "border-box",
  "background-color": "rgba(0, 0, 0, 0)",
  "background-image": "none",
  "background-origin": "padding-box",
  "background-position": "0% 0%",
  "background-repeat": "repeat",
  "background-size": "auto",
  "baseline-shift": "0px",
  "block-size": "auto",
  "border-block-end-style": "none",
  "border-block-end-width": "0px",
  "border-block-start-style": "none",
  "border-block-start-width": "0px",
  "border-bottom-left-radius": "0px",
  "border-bottom-right-radius": "0px",
  "border-bottom-style": "none",
  "border-bottom-width": "0px",
  "border-collapse": "separate",
  "border-end-end-radius": "0px",
  "border-end-start-radius": "0px",
  "border-image-outset": "0",
  "border-image-repeat": "stretch",
  "border-image-slice": "100%",
  "border-image-source": "none",
  "border-image-width": "1",
  "border-inline-end-style": "none",
  "border-inline-end-width": "0px",
  "border-inline-start-style": "none",
  "border-inline-start-width": "0px",
  "border-left-style": "none",
  "border-left-width": "0px",
  "border-right-style": "none",
  "border-right-width": "0px",
  "border-start-end-radius": "0px",
  "border-start-start-radius": "0px",
  "border-top-left-radius": "0px",
  "border-top-right-radius": "0px",
  "border-top-style": "none",
  "border-top-width": "0px",
  "bottom": "auto",
  "box-shadow": "none",
  "box-sizing": "border-box",
  "break-after": "auto",
  "break-before": "auto",
  "break-inside": "auto",
  "buffered-rendering": "auto",
  "caption-side": "top",
  "clear": "none",
  "clip": "auto",
  "clip-path": "none",
  "clip-rule": "nonzero",
  "color-interpolation": "srgb",
  "color-interpolation-filters": "linearrgb",
  "color-rendering": "auto",
  "column-count": "auto",
  "column-gap": "normal",
  "column-rule-style": "none",
  "column-rule-width": "0px",
  "column-span": "none",
  "column-width": "auto",
  "contain-intrinsic-block-size": "none",
  "contain-intrinsic-height": "none",
  "contain-intrinsic-inline-size": "none",
  "contain-intrinsic-size": "none",
  "contain-intrinsic-width": "none",
  "container-name": "none",
  "container-type": "normal",
  "content": "normal",
  "cursor": "auto",
  "cx": "0px",
  "cy": "0px",
  "d": "none",
  "direction": "ltr",
  "dominant-baseline": "auto",
  "empty-cells": "show",
  "fill": "rgb(0, 0, 0)",
  "fill-opacity": "1",
  "fill-rule": "nonzero",
  "filter": "none",
  "flex-basis": "auto",
  "flex-direction": "row",
  "flex-grow": "0",
  "flex-shrink": "1",
  "flex-wrap": "nowrap",
  "float": "none",
  "flood-color": "rgb(0, 0, 0)",
  "flood-opacity": "1",
  "font-kerning": "auto",
  "font-optical-sizing": "auto",
  "font-palette": "normal",
  "font-stretch": "100%",
  "font-style": "normal",
  "font-synthesis-small-caps": "auto",
  "font-synthesis-style": "auto",
  "font-synthesis-weight": "auto",
  "font-variant": "normal",
  "font-variant-caps": "normal",
  "font-variant-east-asian": "normal",
  "font-variant-ligatures": "normal",
  "font-variant-numeric": "normal",
  "font-weight": "400",
  "grid-auto-columns": "auto",
  "grid-auto-flow": "row",
  "grid-auto-rows": "auto",
  "grid-column-end": "auto",
  "grid-column-start": "auto",
  "grid-row-end": "auto",
  "grid-row-start": "auto",
  "grid-template-areas": "none",
  "grid-template-columns": "none",
  "grid-template-rows": "none",
  "height": "auto",
  "hyphenate-character": "auto",
  "hyphens": "manual",
  "image-orientation": "from-image",
  "image-rendering": "auto",
  "inline-size": "auto",
  "inset-block-end": "auto",
  "inset-block-start": "auto",
  "inset-inline-end": "auto",
  "inset-inline-start": "auto",
  "isolation": "auto",
  "justify-content": "normal",
  "justify-items": "normal",
  "justify-self": "auto",
  "left": "auto",
  "letter-spacing": "normal",
  "lighting-color": "rgb(255, 255, 255)",
  "line-break": "auto",
  "list-style-image": "none",
  "list-style-position": "outside",
  "list-style-type": "disc",
  "margin-block-end": "0px",
  "margin-block-start": "0px",
  "margin-bottom": "0px",
  "margin-inline-end": "0px",
  "margin-inline-start": "0px",
  "margin-left": "0px",
  "margin-right": "0px",
  "margin-top": "0px",
  "marker-end": "none",
  "marker-mid": "none",
  "marker-start": "none",
  "mask-type": "luminance",
  "max-block-size": "none",
  "max-height": "none",
  "max-inline-size": "none",
  "max-width": "none",
  "min-block-size": "0px",
  "min-height": "0px",
  "min-inline-size": "0px",
  "min-width": "0px",
  "mix-blend-mode": "normal",
  "object-fit": "fill",
  "object-position": "50% 50%",
  "object-view-box": "none",
  "offset-distance": "0px",
  "offset-path": "none",
  "offset-rotate": "auto 0deg",
  "opacity": "1",
  "order": "0",
  "orphans": "2",
  "outline-offset": "0px",
  "outline-style": "none",
  "outline-width": "0px",
  "overflow-anchor": "auto",
  "overflow-clip-margin": "0px",
  "overflow-wrap": "normal",
  "overflow-x": "visible",
  "overflow-y": "visible",
  "overscroll-behavior-block": "auto",
  "overscroll-behavior-inline": "auto",
  "padding-block-end": "0px",
  "padding-block-start": "0px",
  "padding-bottom": "0px",
  "padding-inline-end": "0px",
  "padding-inline-start": "0px",
  "padding-left": "0px",
  "padding-right": "0px",
  "padding-top": "0px",
  "paint-order": "normal",
  "perspective": "none",
  "perspective-origin": "0px 0px",
  "pointer-events": "auto",
  "position": "static",
  "r": "0px",
  "resize": "none",
  "right": "auto",
  "rotate": "none",
  "row-gap": "normal",
  "ruby-position": "over",
  "rx": "auto",
  "ry": "auto",
  "scale": "none",
  "scroll-behavior": "auto",
  "scroll-margin-block-end": "0px",
  "scroll-margin-block-start": "0px",
  "scroll-margin-inline-end": "0px",
  "scroll-margin-inline-start": "0px",
  "scroll-padding-block-end": "auto",
  "scroll-padding-block-start": "auto",
  "scroll-padding-inline-end": "auto",
  "scroll-padding-inline-start": "auto",
  "scrollbar-gutter": "auto",
  "shape-image-threshold": "0",
  "shape-margin": "0px",
  "shape-outside": "none",
  "shape-rendering": "auto",
  "speak": "normal",
  "stop-color": "rgb(0, 0, 0)",
  "stop-opacity": "1",
  "stroke": "none",
  "stroke-dasharray": "none",
  "stroke-dashoffset": "0px",
  "stroke-linecap": "butt",
  "stroke-linejoin": "miter",
  "stroke-miterlimit": "4",
  "stroke-opacity": "1",
  "stroke-width": "1px",
  "tab-size": "8",
  "table-layout": "auto",
  "text-align": "center",
  "text-align-last": "auto",
  "text-anchor": "start",
  "text-decoration-line": "none",
  "text-decoration-skip-ink": "auto",
  "text-decoration-style": "solid",
  "text-emphasis-position": "over",
  "text-emphasis-style": "none",
  "text-indent": "0px",
  "text-overflow": "clip",
  "text-rendering": "auto",
  "text-shadow": "none",
  "text-size-adjust": "auto",
  "text-transform": "none",
  "text-underline-position": "auto",
  "top": "auto",
  "touch-action": "auto",
  "transform": "none",
  "transform-origin": "0px 0px",
  "transform-style": "flat",
  "transition-delay": "0s",
  "transition-duration": "0s",
  "transition-property": "all",
  "transition-timing-function": "ease",
  "translate": "none",
  "unicode-bidi": "normal",
  "user-select": "auto",
  "vector-effect": "none",
  "vertical-align": "baseline",
  "visibility": "visible",
  "white-space": "normal",
  "widows": "2",
  "width": "auto",
  "will-change": "auto",
  "word-break": "normal",
  "word-spacing": "0px",
  "writing-mode": "horizontal-tb",
  "x": "0px",
  "y": "0px",
  "z-index": "auto",
  "zoom": "1",
}

export const isDefault = (cssProperty: string, value: string): boolean => {
  return !!defaultStyles[cssProperty] && defaultStyles[cssProperty] === value;
}

export const isInheritable = (cssProperty: string): boolean => {
  return [
    'border-collapse',
    'border-spacing',
    'caption-side',
    'color',
    'cursor',
    'direction',
    'empty-cells',
    'font-family',
    'font-size',
    'font-style',
    'font-variant',
    'font-weight',
    'font-size-adjust',
    'font-stretch',
    'font',
    'letter-spacing',
    'line-height',
    'list-style-image',
    'list-style-position',
    'list-style-type',
    'list-style',
    'orphans',
    'quotes',
    'tab-size',
    'text-align',
    'text-align-last',
    'text-decoration-color',
    'text-indent',
    'text-justify',
    'text-shadow',
    'text-transform',
    'visibility',
    'white-space',
    'widows',
    'word-break',
    'word-spacing',
    'word-wrap',
  ].includes(cssProperty);
}

export const isInferable = (styles: CSSStyleDeclaration, cssProperty: string, value: string): boolean => {
  const inferable = {
    'color': [
      'text-decoration-color',
      'text-emphasis-color',
      'column-rule-color',
      'outline-color',
      'border-block-end-color',
      'border-block-start-color',
      'border-bottom-color',
      'border-inline-end-color',
      'border-inline-start-color',
      'border-left-color',
      'border-right-color',
      'border-top-color',
      'caret-color',
    ]
  };

  for (let [source, targets] of _.entries(inferable)) {
    if (!targets.includes(cssProperty))
      continue;

    if (styles.getPropertyValue(source) === value)
      return true;
  }

  return false;
}